### ISSUE TITLE
Guidance on data citation

### ISSUE THREAD

**Issue by karolinahamilton** [CommerceDataService/NZERTF#7]
[DS] Set up guidance on data citation

**Comment by arowla** [comment]
Background info on this dataset: Their first year dataset will be released now. The second year dataset will be released separately, as it's a different set of measurements. Right now they're doing a number of more short-term experiments, and those will probably be released separately.

**Comment by arowla** [comment]
Closing this, as it's really more of an internal thing for NIST to figure out.
